#!/usr/bin/env python3
"""Generate src/s2tables.rs from docs/data/*.json.

The tables are factual constants of Serum2.vst3 2.0.23, dumped at runtime
(docs/s2-runtime-tables.md). Re-run after replacing the JSON dumps.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs" / "data"
OUT = ROOT / "src" / "s2tables.rs"

fx = json.loads((DATA / "fx_desc_table.json").read_text(encoding="utf-8"))
misc = json.loads((DATA / "misc_tables.json").read_text(encoding="utf-8"))
src_enum = json.loads((DATA / "source_enum.json").read_text(encoding="utf-8"))

entries = fx["entries"]
assert len(entries) == 343, len(entries)


def rust_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{out}"'


def f64_lit(v: float) -> str:
    if v != v or v in (float("inf"), float("-inf")):
        raise ValueError(v)
    text = repr(float(v))
    if "e" not in text and "E" not in text and "." not in text:
        text += ".0"
    return text


lines = []
lines.append("// GENERATED by tools/gen_s2tables.py from docs/data/*.json — do not edit by hand.")
lines.append("// Constants of Serum2.vst3 2.0.23 (see docs/s2-runtime-tables.md).")
lines.append("")
lines.append("/// One descriptor of the importer's parameter table (table RVA 0x179B060).")
lines.append("pub struct S2ParamDesc {")
lines.append("    pub idx: u16,")
lines.append("    pub submap: &'static str,")
lines.append("    pub inst: i32,")
lines.append("    pub pid: i32,")
lines.append("    pub kname: Option<&'static str>,")
lines.append("    pub default_v: f64,")
lines.append("    pub min: f64,")
lines.append("    pub max: f64,")
lines.append("    pub step: f64,")
lines.append("    pub cnt: u32,")
lines.append("    pub mode: u32,")
lines.append("    pub fxtype: i32,")
lines.append("    pub options: &'static [&'static str],")
lines.append("}")
lines.append("")
lines.append("pub static S2_PARAM_DESCS: &[S2ParamDesc] = &[")

NO_OPTIONS: dict = {}

for e in entries:
    idx = int(e["index"])
    submap = e["submap"] or ""
    kname = e["kname"]
    opts = e.get("options") or []
    if not isinstance(opts, list):
        opts = []
    opts_lit = ", ".join(rust_str(o) for o in opts)
    if opts_lit:
        opts_field = f"&[{opts_lit}]"
    else:
        opts_field = "&[]"
    kname_field = f'Some("{kname}")' if kname else "None"
    lines.append("    S2ParamDesc {")
    lines.append(f"        idx: {idx},")
    lines.append(f'        submap: "{submap}",')
    lines.append(f"        inst: {int(e['inst'])},")
    lines.append(f"        pid: {int(e['pid'])},")
    lines.append(f"        kname: {kname_field},")
    lines.append(f"        default_v: {f64_lit(e['default'])},")
    lines.append(f"        min: {f64_lit(e['min'])},")
    lines.append(f"        max: {f64_lit(e['max'])},")
    lines.append(f"        step: {f64_lit(e['step'])},")
    lines.append(f"        cnt: {int(e['cnt'])},")
    lines.append(f"        mode: {int(e['mode'])},")
    lines.append(f"        fxtype: {int(e['fxtype'])},")
    lines.append(f"        options: {opts_field},")
    lines.append("    },")
lines.append("];")
lines.append("")
lines.append("/// S1 mod-matrix source-code -> name, id = index + 1 (RVA 0xA20820).")
lines.append("pub static SOURCE_NAMES: &[&str] = &[")
se = src_enum if isinstance(src_enum, list) else src_enum.get("entries", [])
assert len(se) == 59, len(se)
for name in se:
    lines.append(f'    {rust_str(name if isinstance(name, str) else name["name"])},')
lines.append("];")
lines.append("")
lines.append("/// S1 source-code aux remap (RVA 0xA55300, 36 dwords).")
lines.append("pub static AUX_REMAP: &[u32] = &[")
remap = misc["src_remap_0xA55300"]
for v in remap:
    lines.append(f"    {int(v)},")
lines.append("];")
lines.append("")
lines.append("/// Defaults for the state+0x4AE0 block (RVA 0x179F7A0, 31 x f64).")
lines.append("pub static AUX_DEFAULTS: &[f64] = &[")
for d in misc["defaults_179F7A0"]:
    lines.append(f"    {f64_lit(d['value_f64'])},")
lines.append("];")
lines.append("")
lines.append("/// Envelope-loop scales (f32 @0xA55390).")
lines.append("pub static ENV_SCALES: [f32; 4] = [")
for v in misc["env_scale_0xA55390"]:
    lines.append(f"    {f64_lit(v)},")
lines.append("];")
lines.append("")
lines.append("/// Envelope loop S1 master param indexes (i32 @0xA553A0).")
lines.append("pub static ENV_S1PARAMS: [usize; 4] = [")
for v in misc["env_s1param_0xA553A0"]:
    lines.append(f"    {int(v)},")
lines.append("];")
lines.append("")
lines.append('pub const INIT_BODY: &[u8] = include_bytes!("../docs/data/init_body.cbor");')
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT} ({len(lines)} lines)")
